server:
  port: 9090

spring:
  cloud:
    stream:
      bindings:
        input-in-0:
          destination: fromFirst
        input-out-0:
          destination: fromSecond
  datasource:
    url: jdbc:h2:mem:myH2Bd
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
      console:
        enabled: true
        path: /myH2Bd
        settings:
          trace: on
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect