server:
  port: 9090

#rabbitmq settings for Spring Cloud Stream to use
spring:
  cloud:
    stream:
      bindings:
        input-in-0:
          destination: fromFirst
        output-out-0:
          destination: fromSecond